insert into slideshows values (1, 'Interesting pictures', now() );
insert into slides values (1,1,1,1);
insert into slides values (2,2,2,1);
insert into slides values (3,3,3,1);
insert into slides values (4,4,4,1);
insert into slides values (5,5,5,1);
insert into slides values (6,6,6,1);
insert into slides values (7,7,7,1);
insert into slides values (8,8,8,1);
insert into slides values (9,9,9,1);
insert into photos values (1, "balaboa_park.jpg");
insert into photos values (2, "camel.jpg");
insert into photos values (3, "cat_and_candles.jpg");
insert into photos values (4, "hut.jpg");
insert into photos values (5, "mosaic.jpg");
insert into photos values (6, "polar_bear.jpg");
insert into photos values (7, "police.jpg");
insert into photos values (8, "sleeping_dog.jpg");
insert into photos values (9, "stairs.jpg");
